# (C) Serge Victor 2020-2024, GPLv3 License
# 
# recently build version of documents is available on permanent storage disk mounted on /LDP
#
# this file is protected, DO NOT TAMPER without permission from LDP authorised maintainers!
# contact us or create an issue before thinking about any changes.
# #

kind: pipeline
type: docker
name: 🗃 LDP Builder

workspace:
  path: /builder/src
   
steps:
- name: 🗃 Martin's builder - Pull Request only (partial build)
  image: tldp/builder:latest
  volumes:
  - name: LDP
    path: /LDP
  when:
    event:
      include:
      - pull_request
  commands:
  - ldptool --dump-cfg
  - rm -rf /LDP/PR
  - mkdir -p /LDP/PR/BUILD
  - rsync -av /LDP/en /LDP/PR
  - ldptool --loglevel info --builddir /LDP/PR/BUILD --configfile .github/builder.ldptool.cfg --pubdir /builder/PR/en --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /LDP/PR/BUILD --configfile .github/builder.ldptool.cfg --pubdir /builder/PR/en --publish
  - git rev-parse HEAD > /LDP/PR/last-commit-id.txt
  - date > /LDP/PR/build-date.txt

steps:
- name: 🗃 Martin's builder - all revieved commits (full build)
  image: tldp/builder:latest
  volumes:
  - name: LDP
    path: /LDP
  when:
    event:
      exclude:
      - pull_request
    branch:
      include:
      - master
  commands:
  - ldptool --dump-cfg
  - mkdir -p /builder/src/BUILD
  - mkdir -p /builder/src/PUBDIR
  - ldptool --loglevel info --builddir /builder/src/BUILD --configfile .github/builder.ldptool.cfg --pubdir /builder/src/PUBDIR --list
  - ionice -c 3 chrt --idle 0 ldptool --loglevel info --builddir /builder/src/BUILD --configfile .github/builder.ldptool.cfg --pubdir /builder/src/PUBDIR --publish
  - rsync -av --delete-after /builder/src/PUBDIR/ /LDP/en
  - git rev-parse HEAD > /LDP/last-commit-id.txt
  - date > /LDP/build-date.txt

volumes:
- name: LDP
  host:
    path: /LDP

# the happy end.
